services:
  node1:
    image: mysql/mysql-server:8.0
    container_name: node1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./node1:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - mysql-cluster

  node2:
    image: mysql/mysql-server:8.0
    container_name: node2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./node2:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - mysql-cluster

  node3:
    image: mysql/mysql-server:8.0
    container_name: node3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./node3:/var/lib/mysql
    ports:
      - 3309:3306
    networks:
      - mysql-cluster

  router:
    image: mysql/mysql-router:8.0
    container_name: mysql-router
    depends_on:
      - node1
      - node2
      - node3
    environment:
      MYSQL_HOST: node1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./router:/var/lib/mysqlrouter
    ports:
      - 6446:6446
      - 6447:6447
    networks:
      - mysql-cluster

networks:
  mysql-cluster:
    driver: bridge